FROM node:20-alpine as build
WORKDIR /app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx
EXPOSE 5173
COPY ./nginx/prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html