version: '3.8'
services:
  postgres:
    container_name: progreview-postgres-dev
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db
    secrets:
      - postgres_user
      - postgres_db
      - postgres_password
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
  frontend:
    build:
      dockerfile: Dockerfile.dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PUBLIC_URL: http://localhost/cms
      DATABASE_HOST: postgres

secrets:
  postgres_user:
    file: docker_secrets/postgres_user.txt
  postgres_db:
    file: docker_secrets/postgres_db.txt
  postgres_password:
    file: docker_secrets/postgres_password.txt
