version: '3.8'
services:
  nginx:
    image: nginx
    container_name: progreview-nginx
    depends_on:
      - backend
      - frontend
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
  frontend:
    container_name: progreview-frontend
    build:
      context: ./frontend
  backend:
    container_name: progreview-cms
    build:
      context: ./backend
