version: '3.8'
services:
  nginx:
    image: nginx
    container_name: progreview-nginx
    depends_on:
      - backend
      - frontend
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
  frontend:
    container_name: progreview-frontend
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app:cached
  backend:
    build:
      context: ./backend
    container_name: progreview-cms
    volumes:
      - ./backend/src:/opt/src # Changes to the API
      - ./backend/public/uploads:/opt/public/uploads # Uploaded files
      - ./backend/.tmp:/opt/.tmp # Database
