version: '3.8'
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    deploy:
      restart_policy:
        condition: always
  backend:
    build:
      dockerfile: Dockerfile.prod
    deploy:
      restart_policy:
        condition: always
    environment:
      NODE_ENV: production
      PUBLIC_URL: http://theprogressivereview.com/cms
