version: '3.8'
services:
  nginx:
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  frontend:
    build:
      dockerfile: Dockerfile.prod
    restart: on-failure
  backend:
    build:
      dockerfile: Dockerfile.prod
    restart: on-failure
    environment:
      NODE_ENV: production
      PUBLIC_URL: https://www.theprogressivereview.com/cms
  certbot:
    image: certbot/certbot:latest
    container_name: progreview-certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
