version: '3.8'
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
  backend:
    build:
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      PUBLIC_URL: http://theprogressivereview.com/cms
