version: '3.8'
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PUBLIC_URL: http://localhost/cms
