FROM node:16-alpine AS strapi-dev
# Installing libvips-dev for sharp compatibility
RUN apk update && apk add build-base gcc autoconf automake zlib-dev libpng-dev nasm bash vips-dev
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./package-lock.json ./
ENV PATH /opt/node_modules/.bin:$PATH
RUN npm config set fetch-retry-maxtimeout 60000 -g && npm install
COPY ./ .
RUN npm run build
EXPOSE 1337
CMD ["npm", "run", "develop"]